model:
  checkpoint_dir: ./checkpoints_stress_Res18
  checkpoint_name: model.ckpt-XXX000.pt
  load_model: false
  type: Res18
optimizer:
  lr: 0.0002
scheduler:
  gamma: 0.1
  step_size: 1000
training_settings:
  DA_enable: false
  batch_size: 32
  checkpoint_interval: 100
  dataset_dir: ../../../metadata/stress
  drop_last: false
  n_steps: 4000
  n_workers: 0
early_stopper:
  patience: 100
  min_delta: 0
