model:
  checkpoint_dir: ./checkpoints/checkpoints_mmd_FFC_res34
  checkpoint_name: model.ckpt-XXX000.pt
  load_model: false
  type: mmd_FFC_res34
  pretrained_name: model.ckpt-1400.pt
  pretrained_path: ../../../checkpoints/checkpoints_FFC_res34
  alpha: 1
optimizer:
  lr: 0.001
scheduler:
  gamma: 0.5
  step_size: 2000
training_settings:
  DA_enable: false
  batch_size: 64
  checkpoint_interval: 500
  dataset_dir: ../../../metadata
  drop_last: false
  n_steps: 10000
  n_workers: 0
early_stopper:
  patience: 100
  min_delta: 0