model:
  checkpoint_dir: ./checkpoints/checkpoints_mmd_Naive_CNN
  checkpoint_name: model.ckpt-XXX000.pt
  load_model: false
  type: mmd_Naive_CNN
  pretrained_name: model.ckpt-3000.pt
  pretrained_path: ../../../checkpoints/checkpoints_Naive_CNN
  alpha: 1
optimizer:
  lr: 0.001
scheduler:
  gamma: 0.1
  step_size: 1000
training_settings:
  DA_enable: false
  batch_size: 64
  checkpoint_interval: 500
  dataset_dir: ../../../metadata
  drop_last: false
  n_steps: 4000
  n_workers: 0
early_stopper:
  patience: 60
  min_delta: 0
