model:
  checkpoint_dir: ./checkpoints/checkpoints_mmd_Res50
  checkpoint_name: model.ckpt-XXX000.pt
  load_model: false
  type: mmd_Res50
  pretrained_name: model.ckpt-2800.pt 
  pretrained_path: ../../../checkpoints/checkpoints_Res50
  alpha: 1
optimizer:
  lr: 0.001
scheduler:
  gamma: 0.1
  step_size: 1000
training_settings:
  DA_enable: false
  batch_size: 64
  checkpoint_interval: 100
  dataset_dir: ../../../metadata
  drop_last: false
  n_steps: 3000
  n_workers: 0
early_stopper:
  patience: 60
  min_delta: 0