model:
  checkpoint_dir: ./checkpoints_Efficientnet_v2_m
  checkpoint_name: model.ckpt-XXX000.pt
  load_model: false
  type: Efficientnet_v2_m
optimizer:
  lr: 0.001
scheduler:
  gamma: 0.5
  step_size: 1000
training_settings:
  DA_enable: false
  batch_size: 32
  checkpoint_interval: 1000
  dataset_dir: ../../../metadata
  drop_last: false
  n_steps: 50000
  n_workers: 2
early_stopper:
  patience: 20
  min_delta: 0
